### PR TITLE
Update layer_to_numpy method in CostCalculator Class

### PR DESCRIPTION
**Pull request by PaulaBosca**
the arrays attribute of self needed to be defined as self.arrays not simply arrays.

### CODE REVIEW

**Comment by lachlangrose** [comment]
Hi @PaulaBosca, why does the arrays variable need to be defined as an attribute of the cost calculator. It does not get directly used anywhere else in the code and will mean that the raw arrays are stored while an instance of the CostCalculator exists?

**Comment by PaulaBosca** [comment]
A friend of mine who recently tried to import this module into QGIS was receiving attribute errors. The error said that on line 492 (among others methods that later referred to the layer_to_numpy method) that self.arrays.append is incorrect since 'self' does not have the attribute 'arrays'. In my understanding, you have to explicitly state the attribute as self.arrays instead of just 'arrays' for it to be valid within a method.

**Comment by lachlangrose** [comment]
@PaulaBosca self is assigning the variable to the object CostCalculator. So you could access arrays outside of that method, keeping it as arrays means it is only valid when in the scope of that method. I don't think that the issue your friend had was because of this, but it could have been issues stemming from it being difficult to install.... I've made some changes the the installation script today, can you see if the issues still exist and if so past the entire error message here and I will try and fix it. 

I wrote geotrace a long time ago and I would do a lot of things differently now but I am not able to commit too much time to fixing it at the moment.

**Comment by PaulaBosca** [comment]
My friend's is working now with my fix, I tried installing the software and your plugin on my own computer but was getting errors trying to install Cython and I don't use the software so I think that's gonna be it from me, hopefully your fix works!

**Pull request closed without merging**
